@startuml AA_PROJECT_SIMPLIFIED
skinparam dpi 200
hide empty members
title AA_PROJECT - Diagramme de Classes Simplifie (Attributs Essentiels)

class "UCS_USERS" {
  +USER_NAME : varchar(30)
  +REAL_NAME : varchar(40)
  +USER_PWD : varchar(60)
  +USER_ID : float
  +LAST_PWD_CHANGE : float
  +GUID : varchar(38)
}

class "UCS_USERINFO" {
  +APP_ID : float
  +USER_ID : float
  +PROF_ID : float
  +EXPIRATION_DATE : float
  +USER_EXPIRE : varchar(1)
  +USER_ACTIVE : varchar(1)
  +USER_IS_ADMIN : varchar(1)
  +ADDITIONAL_INFO : varchar(200)
}

class "UCS_PROFILES" {
  +PROF_DESCRIPTION : varchar(30)
  +PROF_ID : float
  +INTERVAL_CHANGE_PWD : float
  +MUST_CHANGE_PWD : varchar(1)
  +AUDIT_MODE : varchar(1)
  +PARENT_PROF : float
  +PROF_LEVEL : float
}

class "TabAWProfileAccess" {
  +ProfileUser : varchar(50)
  +CodMod : int
  +LibMod : varchar(50)
  +Actif : bit
  +canAdd : bit
  +canValid : bit
  +canDateLivPrev : bit
  +canExtraData : bit
}

class "UCS_PACCESS" {
  +APP_ID : float
  +FORM_ID : float
  +COMP_ID : float
  +PROF_ID : float
  +SEC_LEVEL : varchar(1)
}

class "UCS_FORMINFO" {
  +PROF_ID : float
  +APP_ID : float
  +FORM_ID : float
  +LAST_UPDATE : float
}

class "UCS_LOGIN_TRACE" {
  +APP_ID : float
  +USER_ID : float
  +LOGIN_DATE_TIME : float
  +LOGOUT_DATE_TIME : float
  +COMPUTER_NAME : varchar(30)
}

class "UCS_AUDIT" {
  +APP_ID : float
  +USER_ID : float
  +FORM_ID : float
  +COMP_ID : float
  +DATE_UTIL : float
  +ADDITIONAL_INFO1 : varchar(1000)
  +ADDITIONAL_INFO2 : varchar(1000)
}

class "Sec_Users" {
  +UserID : int
  +LoginName : varchar(50)
  +FullName : varchar(50)
  +Password : varchar(50)
  +LastAccess : datetime
  +CreatedDate : datetime
}

class "Sec_UserAccess" {
  +ID : int
  +UserName : varchar(50)
  +Permission : varchar(50)
}

class "Sec_Permissions" {
  +Permission : varchar(50)
  +Items : text(2147483647)
  +Action : numeric
  +FormName : varchar(50)
}

class "Sec_Groups" {
  +GroupID : int
  +GroupName : varchar(50)
  +Description : varchar(50)
}

class "Sec_GroupMembers" {
  +UserName : varchar(50)
  +GroupName : varchar(50)
}

class "TabTiers" {
  +IDTiers : uniqueidentifier
  +Niveau : smallint
  +CodTiers : varchar(20)
  +Cin : varchar(10)
  +Raisoc : varchar(255)
  +CodTva : varchar(100)
  +IDTiersCateg : int
  +PUser : varchar(50)
  +SaveDate : datetime
  +DateUser : datetime
  +RaisocAr : nvarchar(255)
  +IDBanque : int
  +CodMagTiers : varchar(20)
  +UserCreate : varchar(50)
  +DateCreatUser : datetime
  +dateUp : datetime
  +CodFour : varchar(30)
  +ProfileUser : varchar(50)
  +codRepresTiers : varchar(50)
}

class "TabTiersAdr" {
  +IDTiers : uniqueidentifier
  +ID : int
  +Adresse : varchar(255)
}

class "TabTiersContact" {
  +IDTiers : uniqueidentifier
  +ID : int
  +Responsable : varchar(255)
  +Tel : varchar(255)
}

class "TabTiersHistory" {
  +IDTiers : uniqueidentifier
  +Niveau : int
  +CodTiers : varchar(20)
  +MDate : datetime
  +Blockage : bit
  +PUser : varchar(50)
  +DateUser : datetime
}

class "TabTiersCateg" {
  +IDTiersCateg : int
  +TierCateg : varchar(50)
  +RemCateg : float
  +Niveau : int
}

class "TabTiersArtPrix" {
  +IDTiers : uniqueidentifier
  +IDArt : uniqueidentifier
  +CodArt : varchar(20)
  +LibArt : varchar(255)
  +PrixVente : float
}

class "TabStock" {
  +IDArt : uniqueidentifier
  +CodArt : varchar(20)
  +LibArt : varchar(255)
  +ExLibArt : varchar(1000)
  +CodFam : varchar(30)
  +LibFam : varchar(50)
  +CodFour : varchar(10)
  +LibFour : varchar(255)
  +CodBar : varchar(255)
  +Qte : numeric
  +PrixAvhat : float
  +PrixVente : float
  +PUser : varchar(30)
  +DateUser : datetime
  +PrixTTC : float
  +CodSFam : varchar(10)
  +CodGrille : varchar(10)
  +QteCom : float
  +PrixDev : float
  +QtePied : int
  +PrixNAchat : float
}

class "TabStockD" {
  +IDArt : uniqueidentifier
  +ID : int
  +CodArt : varchar(30)
  +CodArtD : varchar(30)
  +CodColor : varchar(10)
  +CodTaille : varchar(10)
  +Qte : float
}

class "TabStockComp" {
  +IDCompArt : uniqueidentifier
  +ID : int
  +IDArt : uniqueidentifier
  +CodArt : varchar(20)
  +LibArt : varchar(255)
  +Qte : float
  +CodCompArt : varchar(50)
}

class "TabStockSeries" {
  +IDArt : uniqueidentifier
  +ID : int
  +CodArt : varchar(20)
  +NumSeries : varchar(50)
  +CUser : varchar(50)
  +DatUser : datetime
  +IDDocEnt : uniqueidentifier
  +IDDocSrt : uniqueidentifier
}

class "TabPrixCateg" {
  +IDArt : uniqueidentifier
  +IDTiersCateg : int
  +CodArt : varchar(30)
  +TiersCateg : varchar(50)
  +Prix : float
}

class "TabPrixFamCateg" {
  +IDTiersCateg : int
  +CodFam : varchar(10)
  +TiersCateg : varchar(50)
  +DesFam : varchar(50)
  +Remise : float
}

class "TabLot" {
  +CodOF : varchar(30)
  +CodArt : varchar(20)
  +MDate : datetime
  +NumCmd : varchar(20)
  +CodTiers : varchar(20)
  +LibArt : varchar(255)
  +CodFam : varchar(10)
  +ID : varchar(10)
  +Raisoc : varchar(255)
  +CodColor : varchar(10)
  +CodGrille : varchar(10)
  +PrixOF : money
  +MDatePrev : datetime
  +MDateLivClt : datetime
  +CodTiss : varchar(20)
  +PUser : varchar(30)
  +DateUser : datetime
}

class "TabStatArt" {
  +IDArt : uniqueidentifier
  +LibArt : varchar(255)
  +PrixA : float
  +QteA : float
  +PrixV : float
  +QteV : float
}

class "TabDevm" {
  +Guid : uniqueidentifier
  +Prfx : varchar(50)
  +Sufx : varchar(10)
  +Nf : int
  +IDContact : varchar(40)
  +CodTiers : varchar(20)
  +LibTiers : varchar(100)
  +Valid : bit
  +MntDebit : float
  +MntCredit : float
  +NFav : varchar(30)
  +MntAv : float
  +CodCateg : int
  +CUser : varchar(50)
  +DatUser : datetime
  +MDate : datetime
  +CodMag : varchar(10)
  +CodRepres : varchar(10)
  +DatImp : datetime
  +MntTotDev : float
  +CodDev : varchar(10)
}

class "TabDevd" {
  +Guid : uniqueidentifier
  +NoDetail : int
  +ID : varchar(30)
  +NF : int
  +CodArt : varchar(30)
  +LibArt : varchar(255)
  +ExLibArt : varchar(1000)
  +MntRem : float
  +MntTVA : float
  +MntHT : float
  +MntFodec : float
  +DateBL : datetime
  +Codabar : varchar(50)
  +CodColor : varchar(10)
  +CodTaille : varchar(10)
  +IDArt : varchar(50)
  +MntFrais : float
  +DatImport : datetime
}

class "TabBcvm" {
  +Guid : uniqueidentifier
  +Prfx : varchar(50)
  +Sufx : varchar(10)
  +Nf : int
  +IDContact : varchar(40)
  +CodTiers : varchar(20)
  +LibTiers : varchar(100)
  +Valid : bit
  +MntDebit : float
  +MntCredit : float
  +NFav : varchar(30)
  +MntAv : float
  +CodCateg : int
  +CUser : varchar(50)
  +DatUser : datetime
  +MDate : datetime
  +CodMag : varchar(10)
  +CodRepres : varchar(10)
  +DatImp : datetime
  +MntTotDev : float
  +CodDev : varchar(10)
}

class "TabBcvd" {
  +Guid : uniqueidentifier
  +NoDetail : int
  +ID : varchar(30)
  +NF : int
  +CodArt : varchar(30)
  +LibArt : varchar(255)
  +ExLibArt : varchar(1000)
  +MntRem : float
  +MntTVA : float
  +MntHT : float
  +MntFodec : float
  +DateBL : datetime
  +Codabar : varchar(50)
  +CodColor : varchar(10)
  +CodTaille : varchar(10)
  +IDArt : varchar(50)
  +MntFrais : float
  +DatImport : datetime
}

class "TabBlvm" {
  +Guid : uniqueidentifier
  +Prfx : varchar(50)
  +Sufx : varchar(10)
  +Nf : int
  +IDContact : varchar(40)
  +CodTiers : varchar(20)
  +LibTiers : varchar(100)
  +Valid : bit
  +MntDebit : float
  +MntCredit : float
  +NFav : varchar(30)
  +MntAv : float
  +CodCateg : int
  +CUser : varchar(50)
  +DatUser : datetime
  +MDate : datetime
  +CodMag : varchar(10)
  +CodRepres : varchar(10)
  +DatImp : datetime
  +MntTotDev : float
  +CodDev : varchar(10)
}

class "TabBlvd" {
  +Guid : uniqueidentifier
  +NoDetail : int
  +ID : varchar(30)
  +NF : int
  +CodArt : varchar(30)
  +LibArt : varchar(255)
  +ExLibArt : varchar(1000)
  +MntRem : float
  +MntTVA : float
  +MntHT : float
  +MntFodec : float
  +DateBL : datetime
  +Codabar : varchar(50)
  +CodColor : varchar(10)
  +CodTaille : varchar(10)
  +IDArt : varchar(50)
  +MntFrais : float
  +DatImport : datetime
}

class "TabFavm" {
  +Guid : uniqueidentifier
  +Prfx : varchar(50)
  +Sufx : varchar(10)
  +Nf : int
  +IDContact : varchar(40)
  +CodTiers : varchar(20)
  +LibTiers : varchar(100)
  +Valid : bit
  +MntDebit : float
  +MntCredit : float
  +NFav : varchar(30)
  +MntAv : float
  +CodCateg : int
  +CUser : varchar(50)
  +DatUser : datetime
  +MDate : datetime
  +CodMag : varchar(10)
  +CodRepres : varchar(10)
  +DatImp : datetime
  +MntTotDev : float
  +CodDev : varchar(10)
}

class "TabFavd" {
  +Guid : uniqueidentifier
  +NoDetail : int
  +ID : varchar(30)
  +NF : int
  +CodArt : varchar(30)
  +LibArt : varchar(255)
  +ExLibArt : varchar(1000)
  +MntRem : float
  +MntTVA : float
  +MntHT : float
  +MntFodec : float
  +DateBL : datetime
  +Codabar : varchar(50)
  +CodColor : varchar(10)
  +CodTaille : varchar(10)
  +IDArt : varchar(50)
  +MntFrais : float
  +DatImport : datetime
}

class "TabDocGlobalLines" {
  +Guid : uniqueidentifier
  +NoDetail : int
  +ID : varchar(30)
  +NF : int
  +CodArt : varchar(30)
  +LibArt : varchar(1000)
  +ExLibArt : varchar(1000)
  +MntRem : float
  +MntTVA : float
  +MntHT : float
  +MntFodec : float
  +DateBL : datetime
  +Codabar : varchar(50)
  +CodTaille : varchar(10)
  +CodColor : varchar(10)
  +IDArt : uniqueidentifier
  +MntFrais : float
  +IDContact : uniqueidentifier
  +CodTiers : varchar(20)
  +LibTiers : varchar(255)
  +cuser : varchar(50)
}

class "TabDocRemarq" {
  +IDDoc : uniqueidentifier
  +Remarq0 : varchar(255)
  +Remarq1 : varchar(255)
  +Remarq2 : varchar(255)
  +Remarq3 : varchar(255)
}

class "TabReg" {
  +IDReg : uniqueidentifier
  +IDContact : uniqueidentifier
  +DatReg : datetime
  +CodTiers : varchar(20)
  +LibTiers : varchar(255)
  +MntReg : numeric
  +CUser : varchar(50)
  +DatUser : datetime
  +MntTotPieces : numeric
}

class "TabRegD" {
  +IDReg : uniqueidentifier
  +ID : int
  +Echeance : datetime
  +ModReg : varchar(50)
  +Montant : numeric
  +Valid : bit
  +IDBank : int
  +DatValeur : datetime
  +ValidBloc : bit
  +MntDebit : money
  +MntCredit : money
  +DatPoint : datetime
  +DatVers : datetime
}

class "TabRegF" {
  +IDReg : uniqueidentifier
  +IDPieces : uniqueidentifier
  +NumPiece : varchar(50)
  +MDate : datetime
  +MntPiece : numeric
  +MntReg : numeric
  +MntAdded : numeric
  +ID : int
}

class "TabComptab" {
  +Guid : uniqueidentifier
  +ID : int
  +CodJournal : varchar(20)
  +DesJournal : varchar(100)
  +MDate : datetime
  +LibelleEcriture : varchar(255)
  +IDPices : varchar(255)
  +GuidPiece : uniqueidentifier
}

class "TabComptabPlan" {
  +NumCompte : varchar(20)
  +Libelle : varchar(255)
  +LibelleLong : varchar(255)
  +bDebit : bit
  +bCredit : bit
  +Typecompte : int
}

class "TabComptabModel" {
  +Guid : uniqueidentifier
  +ID : int
  +CodModel : varchar(20)
  +DesModel : varchar(255)
  +CodJournal : varchar(20)
  +LibelleEcriture : varchar(255)
}

class "TabProjet" {
  +IdPojet : uniqueidentifier
  +CodCom : varchar(250)
  +CodCont : varchar(250)
  +CodSoc : varchar(250)
  +Statut : varchar(30)
  +CodFor : varchar(250)
  +Datprc : datetime
  +Datdrc : datetime
  +Datedev : datetime
  +DateBC : datetime
  +nf : int
  +dateSave : date
  +Libstatut : varchar(100)
  +LibCont : varchar(255)
  +LibSoc : varchar(255)
  +CodProjet : varchar(30)
  +LibCom : varchar(30)
  +Datdes : varchar(30)
  +codstatut : int
  +DateBl : date
  +CodDev : varchar(30)
}

class "TabActivite" {
  +Guid : uniqueidentifier
  +Nf : int
  +Mdate : datetime
  +CodTech : varchar(30)
  +DesTech : varchar(250)
  +CodTiers : varchar(30)
  +LibTiers : varchar(100)
  +CodContact : varchar(30)
  +LibContact : varchar(250)
  +DateMail : datetime
  +DateAppel : datetime
  +DateDevis : datetime
  +DateVisite : datetime
  +LibProj : varchar(100)
  +DatPrevDeb : datetime
  +DatPrevFin : datetime
  +MdatePrev : int
  +MdateReal : int
  +User : int
  +DatUser : int
  +DatCreateUser : date
}

class "Objectif" {
  +IdObj : uniqueidentifier
  +TypeObj : varchar(250)
  +DateD : date
  +DateF : date
  +CodTiers : varchar(30)
  +IdCont : uniqueidentifier
  +type : varchar(30)
  +nf : numeric
}

class "TabReclamation" {
  +ID : int
  +NumTicket : nvarchar(50)
  +CodTiers : nvarchar(100)
  +LibTiers : nvarchar(255)
  +Objet : nvarchar(500)
  +TypeReclamation : nvarchar(100)
  +Statut : nvarchar(50)
  +NomTechnicien : nvarchar(255)
  +TechnicienID : int
  +DateOuverture : datetimeoffset
  +DateResolution : datetimeoffset
  +CUser : nvarchar(100)
}

class "TabDI" {
  +IDDI : uniqueidentifier
  +NumDI : int
  +DatDI : datetime
  +CodServ : varchar(10)
  +DescPanne : varchar(255)
  +IDEquip : uniqueidentifier
  +CodSymp : varchar(10)
  +DatCreate : datetime
  +DatModif : datetime
  +CodSServ : int
}

class "TabBT" {
  +IDBT : uniqueidentifier
  +NumBT : int
  +DatBT : datetime
  +CodServ : varchar(10)
  +DescPanne : varchar(255)
  +IDEquip : uniqueidentifier
  +IDInterv : uniqueidentifier
  +CodInterv : varchar(10)
  +CodPanne : varchar(10)
  +DatDebutRep : datetime
  +DatFinrep : datetime
  +CodGroup : varchar(10)
  +DatDI : datetime
  +IDDI : uniqueidentifier
  +CodSymp : varchar(10)
  +DatCreate : datetime
  +DatModif : datetime
  +CodRemed : varchar(10)
  +IDFournis : uniqueidentifier
  +IDBRep : uniqueidentifier
  +CodSServ : int
}

class "TabEquipement" {
  +IDEquip : uniqueidentifier
  +CodEquip : varchar(10)
  +DesEquip : varchar(255)
  +CodFam : varchar(10)
  +CodSFam : varchar(10)
  +IDFournis : uniqueidentifier
  +CodResp : varchar(50)
  +CodServ : varchar(10)
  +PrixAchat : float
  +DatMisServis : datetime
  +DatLimit : datetime
  +CodSite : varchar(10)
  +IDOrgane : uniqueidentifier
  +CodSServ : int
}

class "TabSymptome" {
  +CodSymp : varchar(10)
  +DesSymp : varchar(255)
}

class "TabPanne" {
  +CodPanne : int
  +TypePanne : varchar(255)
}

class "TabService" {
  +CodServ : varchar(10)
  +DesServ : varchar(255)
}

class "TabDevises" {
  +Devise : varchar(10)
  +Sigle : varchar(5)
  +Unit : varchar(10)
  +Cours : float
}

class "TabIntervPrevent" {
  +ID : uniqueidentifier
  +IDIP : uniqueidentifier
  +DatPrevent : datetime
  +IDEquip : uniqueidentifier
  +DatInterv : datetime
  +Valid : bit
  +IDBT : uniqueidentifier
  +DatBT : datetime
  +CodRemed : varchar(10)
}

class "MSGUsers" {
  +ID : int
  +UserName : char(255)
  +FirstName : char(255)
  +LastName : char(255)
  +Organization : char(255)
}

class "MSGContacts" {
  +OwnerID : int
  +ContactID : int
  +ContactNameSource : smallint
  +ContactCustomName : char(255)
}

class "MSGMessages" {
  +ID : int
  +SenderID : int
  +RecipientID : int
  +Delivered : bit
  +DeliveryDate : datetime
  +SendingDate : datetime
  +MessageType : smallint
  +MessageDataSize : int
  +MessageData : image(2147483647)
  +MessageUnicodeText : ntext(1073741823)
}

class "MvtDocs" {
  +ID : int
  +MDate : datetime
  +NF : int
  +CodTiers : varchar(20)
  +LibTiers : varchar(255)
}

class "MvtStock" {
  +ID : int
  +Nf : int
  +MDate : datetime
  +CodArt : varchar(50)
  +LibArt : varchar(255)
  +CodTiers : varchar(20)
  +LibTiers : varchar(255)
  +Qte : float
  +PrixHT : float
}

class "MvtVentes" {
  +ID : int
  +Nf : int
  +MDate : datetime
  +CodArt : varchar(50)
  +LibArt : varchar(255)
  +CodTiers : varchar(20)
  +LibTiers : varchar(255)
  +Qte : float
  +PrixHT : float
  +MntFact : float
}

class "MvtRepres" {
  +CodArt : varchar(30)
  +LibArt : varchar(255)
  +Qt : float
  +CodRepres : varchar(10)
  +DesRepres : varchar(255)
  +QteCom : float
}


' ------------------- RELATIONS PHYSIQUES -------------------
"UCS_USERINFO" "0..*" -- "1" "UCS_USERS" : "appartient a"
"UCS_LOGIN_TRACE" "0..*" -- "1" "UCS_USERS" : "trace login"
"UCS_AUDIT" "0..*" -- "1" "UCS_USERS" : "audit"
"UCS_USERINFO" "0..*" -- "1" "UCS_PROFILES" : "profil"
"UCS_PACCESS" "0..*" -- "1" "UCS_PROFILES" : "acces"
"UCS_FORMINFO" "0..*" -- "1" "UCS_PROFILES" : "formulaire"
"TabAWProfileAccess" "0..*" -- "1" "UCS_PROFILES" : "droits"
"Sec_UserAccess" "0..*" -- "1" "Sec_Users" : "utilisateur"
"Sec_UserAccess" "0..*" -- "1" "Sec_Permissions" : "permission"
"Sec_GroupMembers" "0..*" -- "1" "Sec_Groups" : "groupe"
"Sec_GroupMembers" "0..*" -- "1" "Sec_Users" : "membre"
"TabTiersAdr" "0..*" -- "1" "TabTiers" : "adresse"
"TabTiersContact" "0..*" -- "1" "TabTiers" : "contact"
"TabTiersHistory" "0..*" -- "1" "TabTiers" : "historique"
"TabTiers" "0..*" -- "1" "TabTiersCateg" : "categorie"
"TabTiersArtPrix" "0..*" -- "1" "TabTiers" : "tarif client"
"TabTiersArtPrix" "0..*" -- "1" "TabStock" : "tarif article"
"TabStockD" "0..*" -- "1" "TabStock" : "detail"
"TabStockComp" "0..*" -- "1" "TabStock" : "composition"
"TabStockSeries" "0..*" -- "1" "TabStock" : "serie"
"TabPrixCateg" "0..*" -- "1" "TabStock" : "prix art"
"TabPrixCateg" "0..*" -- "1" "TabTiersCateg" : "prix categ"
"TabPrixFamCateg" "0..*" -- "1" "TabTiersCateg" : "famille categ"
"TabStatArt" "0..*" -- "1" "TabStock" : "stats article"
"TabDevd" "0..*" -- "1" "TabDevm" : "composition"
"TabDevm" "0..*" -- "1" "TabTiers" : "client"
"TabDevd" "0..*" -- "1" "TabStock" : "article"
"TabBcvd" "0..*" -- "1" "TabBcvm" : "composition"
"TabBcvm" "0..*" -- "1" "TabTiers" : "client"
"TabBcvd" "0..*" -- "1" "TabStock" : "article"
"TabBlvd" "0..*" -- "1" "TabBlvm" : "composition"
"TabBlvm" "0..*" -- "1" "TabTiers" : "client"
"TabBlvd" "0..*" -- "1" "TabStock" : "article"
"TabFavd" "0..*" -- "1" "TabFavm" : "composition"
"TabFavm" "0..*" -- "1" "TabTiers" : "client"
"TabFavd" "0..*" -- "1" "TabStock" : "article"
"TabReg" "0..*" -- "1" "TabTiers" : "payeur"
"TabRegD" "0..*" -- "1" "TabReg" : "detail"
"TabRegF" "0..*" -- "1" "TabReg" : "pieces"
"TabRegF" "0..*" -- "1" "TabFavm" : "regle"
"TabComptab" "0..*" -- "1" "TabComptabPlan" : "compte"
"TabComptabModel" "1" -- "0..*" "TabComptab" : "modele"
"TabProjet" "0..*" -- "1" "TabTiers" : "client"
"TabActivite" "0..*" -- "1" "TabProjet" : "projet"
"TabActivite" "0..*" -- "1" "Sec_Users" : "gestionnaire"
"Objectif" "0..*" -- "1" "Sec_Users" : "responsable"
"Objectif" "0..*" -- "0..1" "Objectif" : "parent enfant"
"TabReclamation" "0..*" -- "1" "TabTiers" : "client"
"TabReclamation" "0..*" -- "1" "Sec_Users" : "technicien"
"TabBT" "0..*" -- "1" "TabDI" : "incident"
"TabDI" "0..*" -- "1" "TabEquipement" : "equipement"
"TabBT" "0..*" -- "1" "TabEquipement" : "equipement"
"TabDI" "0..*" -- "1" "TabSymptome" : "Symptome"
"TabBT" "0..*" -- "1" "TabPanne" : "Panne"
"TabBT" "0..*" -- "1" "TabService" : "Service"
"TabBT" "0..*" -- "0..1" "TabIntervPrevent" : "Reference Preventif"
"TabReclamation" "1" -- "0..*" "TabDI" : "Generation DI"
"TabDI" "0..*" -- "1" "TabPanne" : "Panne"
"TabDI" "0..*" -- "1" "TabService" : "Service"
"MSGContacts" "0..*" -- "1" "MSGUsers" : "proprietaire"
"MSGContacts" "0..*" -- "1" "MSGUsers" : "contact"
"MSGMessages" "0..*" -- "1" "MSGUsers" : "expediteur"
"MSGMessages" "0..*" -- "1" "MSGUsers" : "destinataire"

' ------------------- RELATIONS METIER / LOGIQUES -------------------
"TabDevm" "1" .. "0..*" "TabBcvm" : "devis->bc"
"TabDevm" "1" .. "0..*" "TabBlvm" : "devis->bl"
"TabBcvm" "1" .. "0..*" "TabFavm" : "bc->facture"
"TabDocGlobalLines" "0..*" .. "1" "TabDevm" : "source doc"
"TabDocGlobalLines" "0..*" .. "1" "TabBcvm" : "source doc"
"TabDocGlobalLines" "0..*" .. "1" "TabBlvm" : "source doc"
"TabDocGlobalLines" "0..*" .. "1" "TabFavm" : "source doc"
"TabDocRemarq" "0..*" .. "1" "TabDevm" : "remarques"
"TabDocRemarq" "0..*" .. "1" "TabBcvm" : "remarques"
"TabDocRemarq" "0..*" .. "1" "TabBlvm" : "remarques"
"TabDocRemarq" "0..*" .. "1" "TabFavm" : "remarques"
"TabLot" "0..*" .. "1" "TabStock" : "CodArt"
"TabLot" "0..*" .. "1" "TabTiers" : "CodTiers"
"TabPrixFamCateg" "0..*" .. "1" "TabStock" : "CodFam"
"MvtDocs" "0..*" .. "1" "TabTiers" : "stats"
"MvtStock" "0..*" .. "1" "TabTiers" : "stats"
"MvtStock" "0..*" .. "1" "TabStock" : "stats"
"MvtVentes" "0..*" .. "1" "TabTiers" : "stats"
"MvtVentes" "0..*" .. "1" "TabStock" : "stats"
"MvtRepres" "0..*" .. "1" "TabStock" : "stats"
"Objectif" "0..*" .. "1" "TabTiers" : "cible client"
"TabDevm" "0..*" .. "1" "TabDevises" : "Devise"
"TabFavm" "0..*" .. "1" "TabDevises" : "Devise"
@enduml