const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

const BcvMaster = sequelize.define('TabBcvm', {
    Guid: {
        type: DataTypes.UUID,
        primaryKey: true,
        defaultValue: DataTypes.UUIDV4,
        field: 'Guid'
    },
    Prfx: { type: DataTypes.STRING(50), allowNull: true, field: 'Prfx' },
    Sufx: { type: DataTypes.STRING(50), allowNull: true, field: 'Sufx' },
    Nf: { type: DataTypes.INTEGER, allowNull: true, field: 'Nf' },
    IDContact: { type: DataTypes.STRING(100), allowNull: true, field: 'IDContact' },
    CodTiers: { type: DataTypes.STRING(100), allowNull: true, field: 'CodTiers' },
    LibTiers: { type: DataTypes.STRING(255), allowNull: true, field: 'LibTiers' },
    Adresse: { type: DataTypes.STRING(500), allowNull: true, field: 'Adresse' },
    Remarq: { type: DataTypes.STRING(1000), allowNull: true, field: 'Remarq' },
    AssujTiers: { type: DataTypes.STRING(50), allowNull: true, field: 'AssujTiers' },
    TotTva: { type: DataTypes.FLOAT, allowNull: true, defaultValue: 0, field: 'TotTva' },
    TotRem: { type: DataTypes.FLOAT, allowNull: true, defaultValue: 0, field: 'TotRem' },
    TotFodec: { type: DataTypes.FLOAT, allowNull: true, defaultValue: 0, field: 'TotFodec' },
    TotHT: { type: DataTypes.FLOAT, allowNull: true, defaultValue: 0, field: 'TotHT' },
    NetHT: { type: DataTypes.FLOAT, allowNull: true, field: 'NetHT' },
    TotTTC: { type: DataTypes.FLOAT, allowNull: true, defaultValue: 0, field: 'TotTTC' },
    Timbre: { type: DataTypes.FLOAT, allowNull: true, defaultValue: 0, field: 'Timbre' },
    NatReg: { type: DataTypes.STRING(100), allowNull: true, field: 'NatReg' },
    NbrLett: { type: DataTypes.INTEGER, allowNull: true, field: 'NbrLett' },
    Valid: { type: DataTypes.BOOLEAN, allowNull: true, defaultValue: false, field: 'Valid' },
    MntDebit: { type: DataTypes.FLOAT, allowNull: true, defaultValue: 0, field: 'MntDebit' },
    MntCredit: { type: DataTypes.FLOAT, allowNull: true, defaultValue: 0, field: 'MntCredit' },
    Rest: { type: DataTypes.FLOAT, allowNull: true, defaultValue: 0, field: 'Rest' },
    NFav: { type: DataTypes.INTEGER, allowNull: true, field: 'NFav' },
    MntAv: { type: DataTypes.FLOAT, allowNull: true, defaultValue: 0, field: 'MntAv' },
    CodCateg: { type: DataTypes.STRING(100), allowNull: true, field: 'CodCateg' },
    CUser: { type: DataTypes.STRING(100), allowNull: true, field: 'CUser' },
    DatUser: { type: DataTypes.STRING(30), allowNull: true, field: 'DatUser' },
    MDate: { type: DataTypes.STRING(30), allowNull: true, field: 'MDate' },
    CodMag: { type: DataTypes.STRING(100), allowNull: true, field: 'CodMag' },
    DesMag: { type: DataTypes.STRING(255), allowNull: true, field: 'DesMag' },
    CodRepres: { type: DataTypes.STRING(100), allowNull: true, field: 'CodRepres' },
    DesRepres: { type: DataTypes.STRING(255), allowNull: true, field: 'DesRepres' },
    NImpA: { type: DataTypes.INTEGER, allowNull: true, field: 'NImpA' },
    NImpB: { type: DataTypes.INTEGER, allowNull: true, field: 'NImpB' },
    DatImp: { type: DataTypes.STRING(30), allowNull: true, field: 'DatImp' },
    Frais: { type: DataTypes.FLOAT, allowNull: true, defaultValue: 0, field: 'Frais' },
    MntTotDev: { type: DataTypes.FLOAT, allowNull: true, defaultValue: 0, field: 'MntTotDev' },
    Devise: { type: DataTypes.STRING(50), allowNull: true, field: 'Devise' },
    CodDev: { type: DataTypes.STRING(20), allowNull: true, field: 'CodDev' },
    Cours: { type: DataTypes.FLOAT, allowNull: true, defaultValue: 1, field: 'Cours' },
    Cin: { type: DataTypes.STRING(100), allowNull: true, field: 'Cin' },
    LibTiersA: { type: DataTypes.STRING(255), allowNull: true, field: 'LibTiersA' },
    AdresseA: { type: DataTypes.STRING(500), allowNull: true, field: 'AdresseA' },
    CinA: { type: DataTypes.STRING(100), allowNull: true, field: 'CinA' },
    Ville: { type: DataTypes.STRING(255), allowNull: true, field: 'Ville' },
    VilleA: { type: DataTypes.STRING(255), allowNull: true, field: 'VilleA' },
    avanceforf: { type: DataTypes.FLOAT, allowNull: true, defaultValue: 0, field: 'avanceforf' },
    CodChauff: { type: DataTypes.STRING(100), allowNull: true, field: 'CodChauff' },
    DesChauff: { type: DataTypes.STRING(255), allowNull: true, field: 'DesChauff' },
    bTransf: { type: DataTypes.BOOLEAN, allowNull: true, defaultValue: false, field: 'bTransf' },
    DatCreateUser: { type: DataTypes.STRING(30), allowNull: true, field: 'DatCreateUser' },
    bLivr: { type: DataTypes.BOOLEAN, allowNull: true, defaultValue: false, field: 'bLivr' },
    categ: { type: DataTypes.STRING(100), allowNull: true, field: 'categ' },
    type: { type: DataTypes.STRING(100), allowNull: true, field: 'type' },
    DatLiv: { type: DataTypes.STRING(30), allowNull: true, field: 'DatLiv' },
    DiffLiv: { type: DataTypes.INTEGER, allowNull: true, field: 'DiffLiv' },
    lat: { type: DataTypes.FLOAT, allowNull: true, field: 'lat' },
    long: { type: DataTypes.FLOAT, allowNull: true, field: 'long' },
    UserCreate: { type: DataTypes.STRING(100), allowNull: true, field: 'UserCreate' },
}, {
    tableName: 'TabBcvm',
    timestamps: false,
});

module.exports = BcvMaster;
